---
# tasks/canonical/main.yml
- name: Canonical get kubeconfig
  ansible.builtin.command:
    cmd: >-
      k8s config
      --server={{
        'https://[' + _kubernetes_address + ']:6443' if _kubernetes_address is ansible.utils.ipv6 else
        'https://' + _kubernetes_address + ':6443' }}
  changed_when: false
  register: kubernetes_kubeconfig_reg

- name: Canonical set kubeconfig  # noqa: jinja[spacing]
  ansible.builtin.set_fact:
    kubernetes_kubeconfig: "{{ kubernetes_kubeconfig_reg.stdout | from_yaml }}"

- name: Canonical features
  when: >-
    lookup('ansible.builtin.vars', 'kubernetes_' + (item.key | replace('-', '_')) + '_enabled', default=item.value.enabled)
    != item.value.enabled
  ansible.builtin.command:
    cmd: >
      k8s {{ 'disable' if item.value.enabled else 'enable' }} {{ item.key }}
  loop: >-
    {{ ansible_local.kubernetes | dict2items | selectattr('value.enabled', 'defined') | list }}
  changed_when: kubernetes_feature_reg.rc == 0
  register: kubernetes_feature_reg
