---
# tasks/canonical/main.yml
- name: Create settings path
  ansible.builtin.file:
    path: /etc/ansible/etc
    state: directory
    mode: "755"

- name: Install canonical k8s snap
  community.general.snap:
    name: k8s
    classic: true

- name: Get k8s status
  ansible.builtin.command:
    cmd: k8s status --output-format=json
  changed_when: false
  failed_when: false
  register: kubernetes_status_reg

- name: Debug kubernetes status
  ansible.builtin.debug:
    var: kubernetes_status_reg
    verbosity: 1

- name: Bootstrap canonical k8s
  when:
    - kubernetes_status_reg.rc != 0
  block:
    - name: Set kubernetes address  # noqa: jinja[spacing]
      ansible.builtin.set_fact:
        kubernetes_address_default: >-  # noqa: jinja[spacing]
          {%- if kubernetes_host_dualstack and kubernetes_ipv6only %}
          {{ '::1' if kubernetes_environment == 'development' else ansible_facts['default_ipv6']['address'] }}
          {%- else %}
          {{ '127.0.0.1' if kubernetes_environment == 'development' else ansible_facts['default_ipv4']['address'] }}
          {%- endif %}
    # - ansible.builtin.debug: {var: kubernetes_address_default}

    - name: Canonical k8s bootstrap file
      ansible.builtin.template:
        dest: /etc/ansible/etc/canonical.bootstrap.yaml
        lstrip_blocks: true
        mode: "644"
        src: canonical/bootstrap.yaml.j2

    - name: Bootstrap canonical k8s node
      ansible.builtin.command:
        cmd: >
          k8s bootstrap --timeout=10m
          --file=/etc/ansible/etc/canonical.bootstrap.yaml
          --address={{ kubernetes_address_default }}
      changed_when: true
      register: kubernetes_boostrap_reg

    - name: Debug bootstrap
      ansible.builtin.debug:
        var: kubernetes_boostrap_reg
        verbosity: 1

    - name: Wait and get status
      ansible.builtin.command:
        cmd: k8s status --output-format=json --wait-ready
      changed_when: false
      register: kubernetes_bootstrap_status_reg

    - name: Debug kubernetes bootstrap status
      ansible.builtin.debug:
        var: kubernetes_bootstrap_status_reg
        verbosity: 1

- name: Get kubeconfig
  ansible.builtin.command:
    cmd: k8s config
  changed_when: false
  register: kubernetes_kubeconfig_reg

- name: Set kubernetes status and kubeconfig  # noqa: jinja[spacing]
  ansible.builtin.set_fact:
    kubernetes_status: >-  # noqa: jinja[spacing]
      {%- if kubernetes_bootstrap_status_reg.skipped is defined -%}
      {{ kubernetes_status_reg.stdout | from_json }}
      {%- else %}
      {{ kubernetes_bootstrap_status_reg.stdout | from_json }}
      {%- endif %}
    kubernetes_kubeconfig: "{{ kubernetes_kubeconfig_reg.stdout | from_yaml }}"

- name: Feature config
  when:
    - >-
      lookup('ansible.builtin.vars', 'kubernetes_' + (item.key | replace('-', '_')) + '_enabled')
      | default(item.value.enabled)
      != item.value.enabled
  ansible.builtin.command:
    cmd: >
      k8s {{ 'disable' if item.value.enabled else 'enable' }} {{ item.key }}
  loop: "{{ kubernetes_status | dict2items | selectattr('value.enabled', 'defined') | list }}"
  changed_when: kubernetes_feature_reg.rc == 0
  register: kubernetes_feature_reg
