---
# tasks file for snapd
- name: OS variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
        - os_default.yml
      paths:
        - vars

- name: Update package cache if required
  when:
    - ansible_facts.os_family == "Debian"
  ansible.builtin.apt:
    cache_valid_time: 86400
    update_cache: true

- name: Add EPEL repository if required
  when: >
    ansible_facts.os_family == "RedHat" and
    ansible_facts.distribution != "Fedora"
  ansible.builtin.package:
    name: epel-release
    state: present

- name: Install
  ansible.builtin.package:
    name: snapd
    state: present

- name: Enable classic snap support if required
  when:
    - ansible_facts.os_family == "RedHat"
  ansible.builtin.file:
    path: /snap
    src: /var/lib/snapd/snap
    state: link

- name: Enable snapd service
  ansible.builtin.systemd_service:
    enabled: true
    name: "{{ snapd_service_name }}"
    state: started
