---
# Ref. https://docs.ansible.com/projects/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-argument-validation
argument_specs:
  main:
    short_description: Main entrypoint for the kubernetes role
    description: ""
    author:
      - Dean Taylor
    options:
      kubernetes_cni_type:
        type: "str"
        required: false
        choices:
          - calico
          - cilium
          - ""
      kubernetes_environment:
        type: "str"
        required: false
        default: production
        choices:
          - development
          - edge
          - production
      kubernetes_type:
        type: "str"
        required: false
        default: canonical
        choices:
          - canonical
          - k0s
          - microk8s
