---
# tasks file for kubernetes
- name: Operating system variables
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_facts.distribution }}.yml"
        - "{{ ansible_facts.os_family }}.yml"
        - os_default.yml
      paths:
        - vars

- name: Kubernetes type variables
  ansible.builtin.include_vars: "{{ kubernetes_type }}.yml"

- name: Set facts  # noqa: jinja[spacing]
  ansible.builtin.set_fact:
    kubernetes_ctr: >-  # noqa: jinja[spacing]
      {{ kubernetes_ctr_bin }}
      --address {{ kubernetes_containerd_sock | default(kubernetes_containerd_sock_default, true) }}
      --namespace k8s.io
    _kubernetes_v4_cidr_default: "{{ '10.0.0.0/8' | ansible.utils.ipsubnet(24) | random }}"
    _kubernetes_v6_cidr_default: "\
      fd{{ '%02x' % ((127 | random) | int) }}\
      :{{ '%x' % ((32767 | random) | int) }}\
      :{{ '%x' % ((32767 | random) | int) }}\
      :{{ '%x' % ((32767 | random) | int) }}\
      ::/64"
    _kubernetes_cni_type: "{{ kubernetes_cni_type | default(kubernetes_cni_type_default, true) }}"
    kubernetes_host_dualstack: >-
      {{
        (ansible_facts['default_ipv6'] | length > 0) and
        (ansible_facts['default_ipv4'] | length > 0)
      }}
    kubernetes_debian_architecture: >-
      {{
        {'x86_64': 'amd64', 'aarch64': 'arm64'}[ansible_facts.architecture] | default(
          ansible_facts.architecture
        )
      }}

- name: Set kubernetes deployment facts
  ansible.builtin.set_fact:
    _kubernetes_address: >-
      {{
        kubernetes_address | default(
          ansible_facts.default_ipv4.address if not kubernetes_ipv6 else
          ansible_facts.default_ipv6.address if ansible_facts.default_ipv6 | length > 0 else
          ansible_facts.all_ipv6_addresses | ansible.utils.ipaddr('private') | first | default(
          ansible_facts.all_ipv6_addresses | ansible.utils.ipaddr('public') | first
          ),
          true)
      }}
    _kubernetes_pod_cidr: >-
      {{
        kubernetes_pod_cidr | default(
          (_kubernetes_v6_cidr_default | ansible.utils.ipsubnet(108, 0)) if kubernetes_ipv6 else
          (_kubernetes_v4_cidr_default | ansible.utils.ipsubnet(24, 0)),
          true)
      }}
    _kubernetes_service_cidr: >-
      {{
        kubernetes_service_cidr | default(
          (_kubernetes_v6_cidr_default | ansible.utils.ipsubnet(108, 1)) if kubernetes_ipv6 else
          (_kubernetes_v4_cidr_default | ansible.utils.ipsubnet(24, 1)),
          true)
      }}
# - ansible.builtin.debug: {var: _kubernetes_address}
# - ansible.builtin.debug: {var: _kubernetes_pod_cidr}
# - ansible.builtin.debug: {var: _kubernetes_service_cidr}

- name: Hosts file IPv4
  when:
    - "ansible_facts.default_ipv4 | length > 0"
  ansible.builtin.lineinfile:
    insertbefore: BOF
    line: >-
      {{ ansible_facts.default_ipv4.address }}
      {{ ansible_facts.fqdn }}
      {{ ansible_facts.hostname }}
    path: /etc/hosts
    regexp: '^[0-9.]+\s+{{ ansible_facts.hostname }}'
    state: present

- name: Host file IPv6
  when:
    - >-
      ansible_facts.default_ipv6 | length > 0 or
      ansible_facts.all_ipv6_addresses | ansible.utils.ipaddr('private') | length > 0
  ansible.builtin.lineinfile:
    insertbefore: BOF
    line: >-
      {{
        ansible_facts.default_ipv6.address | default(
        ansible_facts.all_ipv6_addresses | ansible.utils.ipaddr('private') | first)
      }}
      {{ ansible_facts.fqdn }}
      {{ ansible_facts.hostname }}
    path: /etc/hosts
    regexp: '^[0-9a-f:]+\s+{{ ansible_facts.hostname }}'
    state: present

- name: Update package cache if required
  when:
    - ansible_facts.os_family == "Debian"
  ansible.builtin.apt:
    cache_valid_time: 86400
    update_cache: true

- name: Ansible
  ansible.builtin.include_tasks: config_ansible.yml

- name: Install snapd if required
  when:
    - kubernetes_type in ["canonical", "microk8s"]
  ansible.builtin.include_role:
    name: ais.core.snapd

- name: Group kubernetes types
  ansible.builtin.group_by:
    key: kubernetes_type_{{ kubernetes_type }}
  changed_when: false

- name: Group kubernetes roles
  ansible.builtin.group_by:
    key: >-
      kubernetes_role_{{
        'undefined' if ansible_local.kubernetes is undefined else (
        'controller' if ansible_local['kubernetes']['ansible_facts']['is_control_plane'] else 'worker'
        )
      }}
  changed_when: false

- name: Group kubernetes elected primary node
  when: >-
    item in groups['kubernetes_type_' + hostvars[item]['kubernetes_type']] |
    ansible.builtin.intersect(groups['kubernetes_role_controller']) |
    sort | first |
    default(groups['kubernetes_type_' + hostvars[item]['kubernetes_type']][0])
  ansible.builtin.add_host:
    name: "{{ item }}"
    groups: "kubernetes_cluster_primary"
  loop: "{{ ansible_play_hosts }}"
  changed_when: false

- name: Set kubernetes type primary
  ansible.builtin.set_fact:
    _kubernetes_canonical_primary: >-
      {{
        groups['kubernetes_type_canonical'] | default([]) |
        ansible.builtin.intersect(groups['kubernetes_cluster_primary']) | first | default('')
      }}
    _kubernetes_k0s_primary: >-
      {{
        groups['kubernetes_type_k0s'] | default([]) |
        ansible.builtin.intersect(groups['kubernetes_cluster_primary']) | first | default('')
      }}
    _kubernetes_microk8s_primary: >-
      {{
        groups['kubernetes_type_microk8s'] | default([]) |
        ansible.builtin.intersect(groups['kubernetes_cluster_primary']) | first | default('')
      }}

- name: Cluster nodes in hosts file
  ansible.builtin.blockinfile:
    block: |
      {% for host in (groups['kubernetes_type_' + kubernetes_type] | sort) %}
      {{ hostvars[host]._kubernetes_address }} {{ hostvars[host].ansible_facts.fqdn }} {{ hostvars[host].ansible_facts.hostname }}
      {% endfor %}
    path: /etc/hosts
    state: present

- name: Kuberentes install
  ansible.builtin.include_tasks: "{{ kubernetes_type }}/install.yml"

- name: Kubernetes cluster bootstrap
  when: >-
    inventory_hostname in groups['kubernetes_cluster_primary']
  ansible.builtin.include_tasks: "{{ kubernetes_type }}/bootstrap.yml"

- name: Kubernetes join
  when: >-
    inventory_hostname not in groups['kubernetes_cluster_primary']
  ansible.builtin.include_tasks: "{{ kubernetes_type }}/join.yml"

- name: Kubernetes image side load
  ansible.builtin.include_tasks: containerd_side_load_images.yml

- name: Configure kubernetes cluster
  when: >-
    inventory_hostname in groups['kubernetes_cluster_primary']
  block:
    - name: Kubernetes cluster setup
      ansible.builtin.include_tasks: "{{ kubernetes_type }}/main.yml"

    - name: Configure coredns dns64
      when:
        - kubernetes_dns64_enabled
        - _kubernetes_address | ansible.utils.ipv6
        - ansible_facts['default_ipv6'] | length > 0
      ansible.builtin.include_tasks: coredns/main.yml

    - name: Configure nat64
      when:
        - kubernetes_nat64_enabled
        - _kubernetes_address | ansible.utils.ipv6
      kubernetes.core.k8s:
        kubeconfig: "{{ kubernetes_kubeconfig }}"
        state: present
        template: "{{ item }}"
      loop:
        - nat64/configmap.yaml.j2
        - nat64/daemonset.yaml.j2

    - name: Configure load balancer
      when:
        - kubernetes_lb_enabled
        - kubernetes_lb_cidrs | length > 0
      ansible.builtin.include_tasks: "{{ kubernetes_cni_type | default(kubernetes_cni_type_default, true) }}/load_balancer.yml"
