---
# defaults file for kubernetes
kubernetes_type: canonical
kubernetes_cni_type: ""
kubernetes_pod_cidr: ""
kubernetes_service_cidr: ""
kubernetes_sans: []
# - custom.kubernetes

kubernetes_ingress_enabled: false
kubernetes_metrics_server_enabled: false

kubernetes_local_storage_enabled: false
kubernetes_local_storage_path: ""

kubernetes_control_plane_taints: []
# - node-role.kubernetes.io/control-plane:NoSchedule

# Gateway API
kubernetes_gateway_enabled: true

# Load Balancer
kubernetes_lb_enabled: false
kubernetes_lb_cidrs: []
# - 10.0.0.0/24
kubernetes_lb_bgp_enabled: false

# https://documentation.ubuntu.com/canonical-kubernetes/latest/snap/howto/install/dev-env/
kubernetes_environment: production
