- name: K0s get stable version
  ansible.builtin.uri:
    return_content: true
    url: https://docs.k0sproject.io/stable.txt
  register: _kubernetes_version_reg

- name: K0s set facts
  ansible.builtin.set_fact:
    _kubernetes_version: >-
      {{ _kubernetes_version_reg.content | trim }}

- name: K0s install
  ansible.builtin.get_url:
    checksum: "sha256:https://github.com/k0sproject/k0s/releases/download\
               /{{ _kubernetes_version }}/sha256sums.txt"
    dest: /usr/local/bin/k0s-{{ _kubernetes_version }}
    mode: "0755"
    url: "https://github.com/k0sproject/k0s/releases/download\
          /{{ _kubernetes_version }}/\
          k0s-{{ _kubernetes_version }}-{{ debian_architecture }}"

- name: K0s default binary link
  ansible.builtin.file:
    path: /usr/local/bin/k0s
    src: /usr/local/bin/k0s-{{ _kubernetes_version }}
    state: link

- name: K0s completion
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      k0s completion bash |tee /etc/bash_completion.d/k0s >/dev/null
    creates: /etc/bash_completion.d/k0s
    executable: /bin/bash

- name: K0s create etc directory
  ansible.builtin.file:
    mode: "0755"
    path: /etc/k0s
    state: directory

- name: K0s /etc/k0s/k0s.yaml exists?
  ansible.builtin.stat:
    path: /etc/k0s/k0s.yaml
  register: _kuberentes_k0s_yaml_reg

- name: K0s get config
  when:
    - _kuberentes_k0s_yaml_reg.stat.exists
  ansible.builtin.slurp:
    src: /etc/k0s/k0s.yaml
  register: _kubernetes_k0s_yaml_reg

- name: K0s config create
  when:
    - not _kuberentes_k0s_yaml_reg.stat.exists
  ansible.builtin.command:
    cmd: k0s config create
  register: _kubernetes_k0s_default_reg
  changed_when: false

- name: K0s get config  # noqa: jinja[spacing]
  ansible.builtin.set_fact:
    _kubernetes_config: >-
      {%- if _kuberentes_k0s_yaml_reg.stat.exists -%}
      {{ _kubernetes_k0s_yaml_reg.content | b64decode | from_yaml }}
      {%- else -%}
      {{ _kubernetes_k0s_default_reg.stdout | from_yaml }}
      {%- endif -%}

- name: K0s combine config
  ansible.builtin.set_fact:
    _kubernetes_config_combine: >-
      {{
        _kubernetes_config |
        ansible.builtin.combine(
          (lookup('ansible.builtin.template', 'k0s/address.yaml.j2') | from_yaml),
          (lookup('ansible.builtin.template', 'k0s/cidr.yaml.j2') | from_yaml) if not _kuberentes_k0s_yaml_reg.stat.exists else {},
          (lookup('ansible.builtin.template', 'k0s/cilium.yaml.j2') | from_yaml) if _kubernetes_cni_type == 'cilium' else {},
          recursive=true
        )
      }}

- name: K0s config
  ansible.builtin.copy:
    content: "{{ _kubernetes_config_combine | to_nice_yaml(indent=2) }}"
    dest: /etc/k0s/k0s.yaml
    mode: "0644"

- name: K0s install controller
  ansible.builtin.command:
    cmd: >
      k0s install controller --enable-worker --no-taints
      {{ "--feature-gates='IPv6SingleStack=true'" if _kubernetes_service_cidr | ansible.utils.ipv6 else "" }}
      --config=/etc/k0s/k0s.yaml
    creates: /var/lib/k0s
  register: _kubernetes_k0s_install_reg

- name: K0s start  # noqa: no-handler
  when:
    - _kubernetes_k0s_install_reg.changed
  ansible.builtin.command:
    cmd: k0s start
  changed_when: true

- name: K0s wait for status
  ansible.builtin.wait_for:
    path: /run/k0s/status.sock
    state: present
    timeout: 60

- name: K0s get kubeconfig
  ansible.builtin.command:
    cmd: k0s kubectl config view --raw
  changed_when: false
  register: _kuberentes_kubeconfig_reg

- name: K0s set kubeconfig
  ansible.builtin.set_fact:
    kubernetes_kubeconfig: "{{ _kuberentes_kubeconfig_reg.stdout | from_yaml }}"
