- name: K0s get kubeconfig
  ansible.builtin.command:
    cmd: k0s kubectl config view --raw
  changed_when: false
  register: _kubernetes_kubeconfig_reg

- name: K0s set kubeconfig
  ansible.builtin.set_fact:
    kubernetes_kubeconfig: "{{ _kubernetes_kubeconfig_reg.stdout | from_yaml }}"
